(()=>{const P={"37546":"sexy-pickford","118082":"battle-continues"},root=location.pathname.match(/\/(sexy-pickford|battle-continues)\//)?"../":"";
const j=async p=>{let r=await fetch(p+(p.includes("?")?"&":"?")+"v="+Date.now());if(!r.ok)throw Error(p);return r.json()};
const wanted=()=>new URLSearchParams(location.search).get("league")||(location.pathname.includes("battle-continues")?"118082":location.pathname.includes("sexy-pickford")?"37546":null);
const active=()=>document.querySelector(".tab.active")?.dataset.id||wanted()||"37546";
async function stamp(){try{let d=await j(root+"data/latest.json"),h=document.querySelector(".standings-section .section-head");if(!h)return;let e=document.querySelector("#standingsSnapshotNote");if(!e){e=document.createElement("div");e.id="standingsSnapshotNote";e.className="standings-snapshot";h.appendChild(e)}e.textContent="Standings snapshot: "+new Date(d.generated_at).toLocaleString("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})+" · Updates daily"}catch(e){}}
async function chart(){let host=document.querySelector("#seasonProgressChart");if(!host)return;try{let m=await j(root+"data/manifest.json"),ss=(await Promise.all((m.official_snapshots||[]).map(p=>j(root+p).catch(()=>null)))).filter(Boolean),lid=active(),g=new Map;
for(let s of ss){let l=s.leagues?.find(x=>String(x.league_id)===lid);if(!l||!s.gameweek)continue;let t=new Date(s.generated_at||s.snapshot_date||0).getTime(),o=g.get(+s.gameweek);if(!o||t>=o.t)g.set(+s.gameweek,{t,rows:l.standings||[]})}
let gs=[...g.keys()].sort((a,b)=>a-b);if(gs.length<2){host.innerHTML='<div class="empty">Progress chart will appear after two recorded gameweeks.</div>';return}
let ms=new Map;for(let gw of gs)for(let x of g.get(gw).rows){let id=String(x.entry_id);if(!ms.has(id))ms.set(id,{name:x.manager_name,pts:[]});ms.get(id).pts.push({gw,pos:+x.league_position})}
let top=[...ms.values()].sort((a,b)=>(a.pts.at(-1)?.pos||999)-(b.pts.at(-1)?.pos||999)).slice(0,8),max=Math.max(1,...top.flatMap(x=>x.pts.map(p=>p.pos))),W=900,H=330,L=46,R=18,T=24,B=44,X=gw=>L+gs.indexOf(gw)/(gs.length-1)*(W-L-R),Y=p=>T+(p-1)/Math.max(1,max-1)*(H-T-B),c=["#25d0d8","#b48cff","#55d98b","#ffd166","#ff7b9c","#79a7ff","#f6a85f","#c7d36f"],svg=`<svg viewBox="0 0 ${W} ${H}">`;
for(let gw of gs)svg+=`<text x="${X(gw)}" y="${H-16}" text-anchor="middle" class="chart-axis">GW${gw}</text>`;for(let p=1;p<=max;p++)svg+=`<line x1="${L}" y1="${Y(p)}" x2="${W-R}" y2="${Y(p)}" class="chart-grid"/><text x="${L-12}" y="${Y(p)+4}" text-anchor="end" class="chart-axis">${p}</text>`;
top.forEach((x,i)=>{svg+=`<polyline points="${x.pts.map(p=>X(p.gw)+","+Y(p.pos)).join(" ")}" fill="none" stroke="${c[i]}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>`;x.pts.forEach(p=>svg+=`<circle cx="${X(p.gw)}" cy="${Y(p.pos)}" r="4" fill="${c[i]}"/>`)});svg+="</svg>";host.innerHTML=svg+`<div class="chart-legend">${top.map((x,i)=>`<span><i style="background:${c[i]}"></i>${x.name}</span>`).join("")}</div>`}catch(e){host.innerHTML='<div class="empty">Unable to load season progress.</div>'}}
function section(){if(document.querySelector("#seasonProgressSection"))return;let s=document.querySelector(".standings-section");if(!s)return;let n=document.createElement("section");n.className="section";n.id="seasonProgressSection";n.innerHTML='<div class="section-head"><div><div class="eyebrow">Season so far</div><h2>League position progress</h2></div><div class="section-note">Top 8 current managers</div></div><div id="seasonProgressChart" class="progress-chart"></div>';s.before(n)}
addEventListener("load",()=>setTimeout(()=>{let w=wanted();if(w){let b=document.querySelector(`.tab[data-id="${w}"]`);if(b&&!b.classList.contains("active"))b.click()}document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>setTimeout(chart,50)));section();stamp();chart()},300))})();